---
- hosts: all
  become: yes
  tasks:
   - name: Pinging all the hosts in the file
     ping:
   - name: update packages on ubuntu
     apt:
       name: git
       state: present
   - name: Installing Tree
     apt:
       name: tree
       state: present