---
- hosts: all
  become: yes
  tasks:
  - name: update packages and install apache
    apt:
      name: apache2
      enabled: yes
      state: present
    notify:
    - restart apache
    when: ansible_os_family == "Debian"
  - name: Installing php Package
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mob-php
      - php-mcrypt
      - php-mysql
    notify:
    - restart apache
    when: ansible_os_family == "Debian"
  handlers:
  - name: restart apache
    service:
    name: apache2
    enabled: yes
    state: restarted
    when: ansible_os_family == "Debian"